### ISSUE TITLE
Another solution using only sqlite3

### ISSUE THREAD

**Issue by mingodad** [gstamatakis/Hashcode-VoskosTeam#1]
Hello !
I did not participated officially on the Hashcode 2018 but implemented a solution for it that only requires sqlite3 command line and the data files, and thought it could be of your interest to know about it and maybe give you ideas to improve your and maybe mine.

https://github.com/mingodad/sqlite3-hashcode-2018

Cheers !

**Comment by gstamatakis** [comment]
Hello @mingodad ,
We have read and understood some parts of your code and although some of the logic behind it seems good we would like to ask you a few things because we strongly believe that the use of more declarative languages in competitions such as Hashcode is the future. First of all, did this code produce any valid results and if so what was the score?Secondly, you should consider assigning a "score" to every ride-vehicle pair ,taking into account every given constraint (distance,time,bonus..). The reason why we used a scoring function is because it basically requires a single sort (to get the item with the highest score) and doesn`t directly require sorting in every dimension.Finally, we are confident that in order to get the best results out of each input file,one could use different scheduling algorithms or even heuristic algorithms. I understand that our approach can`t be easily implemented in an sqlite env but we highly recommend the usage of a global (weighted) scoring function. Feel free to expand this thread.

-The team

**Comment by mingodad** [comment]
Hello !
Yes it produces valid results, for brevity here is the output of "a_example.in" (with a bit of formatting):
```
Result Status
'all' 		| count | total_size | total_between_rides | total_waiting_steps | total_delay_steps
all		| 3 	| 8 	| 6 	| -9 	| 9
assigned	| 3 	| 8 	| 6 	| -9 	| 9
ontime	| 0 	|  	|  	|  	| 
possible	| 3 	| 8 	| 6 	| -9 	| 9
----

result_rides
1 2
2 0 1
```
And now that you've mentioned using a weighted sore I can see that my solution on this data do not assign an ontime car to the first ride that could be done if I used a different sort function.

Thank you so much ! You already helped me see one issue that I was not aware so far.

I just added the need code to calculate and show the scores and they are:
```
a_example.in	8
b_should_be_easy.in	176877
c_no_hurry.in			12139456
d_metropolis.in		10995920
e_high_bonus.in		21465945

Total				44778206
```

**Comment by gstamatakis** [comment]
@mingodad 
Glad we could help, your results are very good. I was also wondering how long does it take to run all 5 input files. I am not aware of any profiling tools for .nut files but you may want to check function execution times and/or divide tasks to more threads. Good luck and feel free to ask anything.

-The team

**Comment by mingodad** [comment]
Thank you again !
The time to solve each data set depends on the machine, on my case a simple Atom @1.66GHZ
the biggest one took around 16 seconds.
All of then could take would take less than a minute on my Atom machine  for the sqlite3 one the .nut does the same thing but is a bit faster around 10% only.

**Comment by gstamatakis** [comment]
That is amazing, our solution takes about ~12min in a modern i5 laptop. We should really consider moving into a more declarative language..

**Comment by mingodad** [comment]
So my solution on your laptop would be maybe 20 seconds for all, that's really a big difference.
You can try it (after edit it to use for example d_metropolis.in the heavy one):
```
time sqlite3 < hashcode2018.sql
```

**Comment by gstamatakis** [comment]
Thanks, looking forward to see the your code in the future.
